### ISSUE TITLE
Unspecified dependencies

### ISSUE THREAD

**Issue by rmhubley** [ParBLiSS/kmerind#1]
I am having trouble compiling kmerind.  The errors have to do with missing dependencies.  Here is what I have tracked down so far:

kmerind-build/tommyds  ( https://github.com/amadvance/tommyds )
kmerind-build/sparsehash ( https://github.com/sparsehash/sparsehash )
kmerind-build/mxx ( https://github.com/patflick/mxx )

I am not sure I grabbed the right versions but using the Master branches from the above I am able to get past all the missing files.  Now I am against some macro problems ( perhaps a problem with the versions I used above? ):

In file included from /home/rhubley/projects/kmerind-TCBB/src/containers/fsc_container_utils.hpp:32:0,
                 from /home/rhubley/projects/kmerind-TCBB/src/containers/densehash_map.hpp:44,
                 from /home/rhubley/projects/kmerind-TCBB/test/benchmark/BenchmarkHashTables.cpp:18:
/home/rhubley/projects/kmerind-TCBB/test/benchmark/BenchmarkHashTables.cpp: In function 'int main(int, char**)':
/home/rhubley/projects/kmerind-TCBB/test/benchmark/BenchmarkHashTables.cpp:1208:27: error:'test' was not declared in this scope
   BL_BENCH_COLLECTIVE_END(test, "unordered_map", count, comm);
                           ^

**Comment by tcpan** [comment]
My apologies for the delayed response.

You may have already figured this out, but my guess is that the git submodules for these are not downloaded.  To initialized and download the submodules,

1. go to your source checkout directory
2. run "git submodule init"
3. run "git submodule update"

Then return to the build directory and call "make"

Please let me know if this fixes the problem or if you have any further questions.  Thank you.
